### ISSUE TITLE
Why not use pssh?

### ISSUE THREAD

**Issue by jacobbridges** [psychobunny/paralleler#1]
Just in case you didn't know, a Linux tool already exists for executing bash commands in parallel across multiple servers: http://linux.die.net/man/1/pssh

**Comment by psychobunny** [comment]
Thanks, I know about it already, I had something completely different in mind here :)

**Comment by jacobbridges** [comment]
Sweet! Just thought I'd save you some work if you hadn't found it. Have fun!
